@TitleId = 
@Secret = 
#GetEntityToken
POST https://{{TitleId}}.playfabapi.com/Authentication/GetEntityToken
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406
X-SecretKey: {{Secret}}

{
    "test": "test"
}

@EntityToken = 

###

#Set / Create Matchmaking queue
@QueueName = StringTest
POST https://{{TitleId}}.playfabapi.com/Match/SetMatchmakingQueue?
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406
X-EntityToken: {{EntityToken}}

{
    "MatchmakingQueue": {
        "Name": "{{QueueName}}",
        "MinMatchSize": 2,
        "MaxMatchSize": 4,
        "ServerAllocationEnabled": false,
        "StringEqualityRules": [
            {
                "Attribute": {
                    "Path": "version",
                    "Source": "User"
                },
                "Weight": 1,              
                "Name": "VersionRequiered",
                "AttributeNotSpecifiedBehavior": "MatchAny"
            }
        ],
        "StatisticsVisibilityToPlayers": {
            "ShowNumberOfPlayersMatching": true,
            "ShowTimeToMatch": true
        }
    }
}

###

#Get PlayFabUser Auth Entity token
POST https://titleId.playfabapi.com/Client/LoginWithCustomID
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406

{
    
    "CustomId": "",
    "TitleId": "{{TitleId}}",
}

###

@PlayerEntityToken = 
@PlayerPlayerId = 
#Create matchmaking ticket
POST https://{{TitleId}}.playfabapi.com/Match/CreateMatchmakingTicket
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406
X-EntityToken: {{PlayerEntityToken}}

{
  "Creator": {
      "Entity" : {
          "Id": "{{PlayerPlayerId}}",
          "Type": "title_player_account"
      },
      "Attributes": {
          "DataObject": {
              "version": "1"
          }
      }

  },
  "MembersToMatchWith": [],
  "GiveUpAfterSeconds": 1000,
  "QueueName": "{{QueueName}}"
}

@TicketId = 

###
#PLayer2
@player2CustomId = 

POST https://titleId.playfabapi.com/Client/LoginWithCustomID
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406

{
    
    "CustomId": "{{player2CustomId}}",
    "TitleId": "{{TitleId}}",
}

###
@player2Session = 
@player2PlayerID = 

POST https://{{TitleId}}.playfabapi.com/Match/CreateMatchmakingTicket
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406
X-EntityToken: {{player2Session}}

{
  "Creator": {
      "Entity" : {
          "Id": "{{player2PlayerID}}",
          "Type": "title_player_account"
      },
      "Attributes": {
          "DataObject": {
              "version": "1"
          }
      }

  },
  "MembersToMatchWith": [],
  "GiveUpAfterSeconds": 1000,
  "QueueName": "{{QueueName}}"
}

###
#Get Matchmaking ticket
POST https://titleId.playfabapi.com/Match/GetMatchmakingTicket
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406
X-EntityToken: {{PlayerEntityToken}}

{
    "EscapeObject": false,
    "QueueName": "{{QueueName}}",
    "TicketId": "{{TicketId}}"
}

###

#Cancel Matchmaking ticket
POST https://titleId.playfabapi.com/Match/CancelMatchmakingTicket
Content-Type: application/json
Accept-Encoding: gzip
X-PlayFabSDK: PostmanCollection-0.121.210406
X-EntityToken: {{PlayerEntityToken}}

{
    "QueueName": "{{QueueName}}",
    "TicketId": "{{TicketId}}"
}